version: '3.7'
services:
  mysql:
    #build: ./databases

    image: mysql:8.0
    ports:
      - '3306:3306'
    #command: docker cp ./databases/schema.sql
    volumes:
      #- ./data:/var/lib/mysql
      - ./databases:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
